version: "3"
services:
  web:
    #remplazar username/repo:tag con el nombre y imagen
    #image: username/repo:tag
    image: jalbertomr/lab_1:python_app_1
    deploy:
      replicas: 5
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - "5000:4000"
    networks:
      - webnet
networks:
  webnet:
